Q1. Generate a random 1000 * 1000 multi-dimensional array A with numbers
ranging from 0 to 101, Compute the sum of all elements in the array A that are
greater than the median of the entire array.

Output:Sum of elements greater than the median: 37344112

In [1]:
import numpy as np
A = np.random.randint(0, 101, (1000, 1000))
median_A = np.median(A)
sum_greater_than_median = np.sum(A[A > median_A])
print("Sum of elements greater than the median:", sum_greater_than_median)


Sum of elements greater than the median: 37344112


Q2. Reshape the array A into a shape (500, 2000) and calculate the sum of
elements along the new dimension axis=1 (i.e., for each row in the reshaped
array).

Output:Sum of elements along axis=1 for each row: [ 97876 100666  97232  98112 102490  98223  99237 101093  99904  99609
  99236 100536  98314  99080 100326 101536  99115  98751 100146  98085
  99129  98615 100681  98096 100593 101096 101149 101421 100921  99479
  97761  97331  98757  99105 100040 100517  99453 100740  98409  98706
 100093  99127 101099  99866 100779 101764  97514 100241  99851 100672
 101286  98706  99486  99241 101154 100123 103275 100335  98375  98845
  97673  97119 101339  99262 101008  99610  99039 100848  99024  97706
 100496 101384  99638  99286  99135  98804  99132 100358  99970 101089
 101899 100796  95886  99249  99659  99978 101584  99900  99835  99966
 102149 100438  99141 101920  98789  96934  97966  99966  98266  98999
 102170 100827 102113  98205 102663  98948  99463 101108  99586 104179
 100083 100431  99985  98779  99779 101716 101505 101647 102258  98810
  99184 100631  99338 100093  99861 100931 100808  97888  99628 102501
 101863 100635  97200  98585  98736  98284  98822 100276  99759  98160
 101315 103121  98067 100402  98713  96672 100626  99659  99705  99201
 100039  98432  98661 100293 100116 100711  99667  99970 103168 100710
  98246  98801  99152  97294  98380 102037  99573 101565 101826  99873
  98001 100599  99222 100369 101211 100121  99354  98743  99431  99262
 101752 102490 102361 100163 100771 100242 100580 102015 102090 101581
 101121 101093 102234  99210 100914 101520  99938  99505 100947  99489
 101116 101130  99168  98024  99462  99339 100013  98976 100294  99130
  98671  99056 101095  99402  99986  98964  99291 100421 100318 101468
 102761  99581 100354  98778  98457  98396 100676 101168 100771 101088
  99988  99690  99984 100559 101274  99790  98158  99311 100489 101126
 101904  99682 100575 101385  99115 101407  99577  98460 100397  98898
  99792  98508  98917 100877  98200  99818  99741 100837 101028 101045
  97486 101263  98688  97459  99705 101190  98637 101202  99808  99886
  99145  99261 101181 100614  99293 100704  98956  99846 100575  99525
  99177 100677 101188 100420 100204 100610 102461 101069  99904 100631
 101416 100009 100970 100929  99251 100740 100042 100158  98952 100549
 101339 100481  99709  99739 101159  98124 100192  96643  98251 100073
  99510 103163 100694 101143 101095  98974  97674  97932  99550 100952
  99196  99653  99990  99493 100666  99904 101811 100211 100984  99423
  98246 100228  98423 101794 101365  97160 100292 100210  97091 101678
  99304 100709 100778 101578 102298 101121 101569  98053  98356  98575
 100319 100058 100040  97848  97348 100994  98791  98700  99636 100024
 101623 102266  98746  99866 102134 101385  97978  99723  99964  99930
 100927 101273 100725  98449  99275  97069  97160  99568 100841  99275
 102040  99569 102166 100338  99650  99419  98648 100625  99710  99967
 102593  98841  98114 103063 101053  98597 101692 100059  99070 101899
 101475  99009  99482 100286 102315  98771 100512  99221 101220 101172
 100744  99626  98622 100057 101086 103596  98433  98254 100333  99832
 101601 100124  99049 101402 100552 100344 101221  99714  99173  98822
 100082 101981  98369 101304 100888  99253  98886 101865 101259 100177
 101219 100285 101081 100259  98763  98336  99913  99387 100798  98964
  97781  98929  99353  98129  99316 103024  97870 100754 100535  99663
 100534 100374 100493  99365  98332 100090  99388 102454 100937 100079
 101562  99043 101522 102544  99669  99989 100394  99644 101556 101162
 101265  97093 101241  98453 102348  98107 101428  98577 102279 102274
  99732  99943  98385  96486 100058 101763  98693 103098  98511  99369

In [2]:
import numpy as np
A = np.random.randint(0, 101, size=(1000, 1000))
reshaped_A = A.reshape(500, 2000)
row_sums = np.sum(reshaped_A, axis=1)
print("Sum of elements along axis=1 for each row:", row_sums)


Sum of elements along axis=1 for each row: [ 97876 100666  97232  98112 102490  98223  99237 101093  99904  99609
  99236 100536  98314  99080 100326 101536  99115  98751 100146  98085
  99129  98615 100681  98096 100593 101096 101149 101421 100921  99479
  97761  97331  98757  99105 100040 100517  99453 100740  98409  98706
 100093  99127 101099  99866 100779 101764  97514 100241  99851 100672
 101286  98706  99486  99241 101154 100123 103275 100335  98375  98845
  97673  97119 101339  99262 101008  99610  99039 100848  99024  97706
 100496 101384  99638  99286  99135  98804  99132 100358  99970 101089
 101899 100796  95886  99249  99659  99978 101584  99900  99835  99966
 102149 100438  99141 101920  98789  96934  97966  99966  98266  98999
 102170 100827 102113  98205 102663  98948  99463 101108  99586 104179
 100083 100431  99985  98779  99779 101716 101505 101647 102258  98810
  99184 100631  99338 100093  99861 100931 100808  97888  99628 102501
 101863 100635  97200  98585  9873

Q3. Normalize each row of the reshaped array by dividing it by the sum of its
elements. Then, compute the standard deviation of the normalized rows.
Q1(a). Normalize the dataset to have values between 0 and 1.
(b). Compute the dot product of the dataset with itself.
Q2(a). Calculate the element-wise square root of the dataset.
(b). Perform matrix multiplication (i.e., the matrix product) of the dataset with
its transpose.

In [4]:
import numpy as np

# Provided data array
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# 1. Normalize each row of the reshaped array and compute the standard deviation of the normalized rows.
# Normalize each row by dividing by the sum of elements in the row
row_sums = np.sum(data, axis=1, keepdims=True)
normalized_rows = data / row_sums

# Compute the standard deviation of the normalized rows
std_dev_normalized_rows = np.std(normalized_rows, axis=1)

print("Normalized Rows:\n", normalized_rows)
print("Standard Deviation of Normalized Rows:", std_dev_normalized_rows)
print("-" * 50)

# 2(a). Normalize the dataset to have values between 0 and 1
min_val = np.min(data)
max_val = np.max(data)

normalized_data_0_1 = (data - min_val) / (max_val - min_val)

print("Normalized dataset between 0 and 1:\n", normalized_data_0_1)
print("-" * 50)

# 2(b). Compute the dot product of the dataset with itself
dot_product = np.dot(data, data)

print("Dot Product of the dataset with itself:\n", dot_product)
print("-" * 50)

# 3(a). Calculate the element-wise square root of the dataset
sqrt_data = np.sqrt(data)

print("Element-wise square root of the dataset:\n", sqrt_data)
print("-" * 50)

# 3(b). Perform matrix multiplication of the dataset with its transpose
matrix_product = np.matmul(data, data.T)

print("Matrix multiplication of dataset with its transpose:\n", matrix_product)


Normalized Rows:
 [[0.1        0.2        0.3        0.4       ]
 [0.19230769 0.23076923 0.26923077 0.30769231]
 [0.21428571 0.23809524 0.26190476 0.28571429]
 [0.22413793 0.24137931 0.25862069 0.27586207]]
Standard Deviation of Normalized Rows: [0.1118034  0.04300131 0.02661986 0.01927645]
--------------------------------------------------
Normalized dataset between 0 and 1:
 [[0.         0.06666667 0.13333333 0.2       ]
 [0.26666667 0.33333333 0.4        0.46666667]
 [0.53333333 0.6        0.66666667 0.73333333]
 [0.8        0.86666667 0.93333333 1.        ]]
--------------------------------------------------
Dot Product of the dataset with itself:
 [[ 9000 10000 11000 12000]
 [20200 22800 25400 28000]
 [31400 35600 39800 44000]
 [42600 48400 54200 60000]]
--------------------------------------------------
Element-wise square root of the dataset:
 [[ 3.16227766  4.47213595  5.47722558  6.32455532]
 [ 7.07106781  7.74596669  8.36660027  8.94427191]
 [ 9.48683298 10.         10.488088